en = {
    "byLaps": "By Laps",
    "byStint": "By Stint",
    "calculate": "Calculate",
    "formationLap": "Formation Lap",
    "lapTime": "Lap Time",
    "laps": "Laps",
    "options": "Options",
    "perLap": "Per Lap",
    "save": "Save",
    "stintLength": "Stint/Race Length",
    "estLaps": "Estimated Laps",
    "gallons": "Gallons",
    "litres": "Litres",
    "risky": "Risky",
    "safe": "Safe",
    "car": "Car",
    "carClass": "Class",
    "conditions": "Conditions",
    "selectCombo": "Select Combination",
    "selections": "Selections",
    "track": "Track",
    "clearData": "Clear Data",
    "language": "Language",
    "leaveReview": "Leave a Review",
    "sendSuggestion": "Send a Suggestion",
    "thankYou": "Thank You",
    "units": "Units",
    "dry": "Dry",
    "damp": "Damp",
    "wet": "Wet",
    "themeOptions": "Theme Options",
    "light": "Light",
    "dark": "Dark",
    "system": "System",
    "success": "Success",
    "error": "Error"
}


translated = {
    'Calculate':	'Calcular',
    'Save':	'Salvar',
    'Saved':	'Salvo',
    'Error':	'Erro',
    'Please fill in all values':	'Por favor, preencha todos os valores',
    'Suggestions':	'Seugestões',
    'Settings':	'Opções',
    'Lap Time':	'Tempo de volta',
    'Stint/Race Length':	'Tempo de Corrida (Stint)',
    'Litres per lap':	'Litros por volta',
    'Risky':	'Combustível (Mínimo)',
    'Safe':	'Combustivel (Seguro)',
    'Formation Lap':	'Volta de apresentação',
    'Simple':	'Simples',
    'Language':	'Idioma',
    'Upgrade to premium':	' Obtenha a versão premium',
    'Premium version':	'versão premium',
    'Theme Options':	'Opções de tema',
    'Dark mode':	' Alterar para modo escuro',
    'Use system default theme':	' Usar tema padrão do sistema',
    'Fuel Calculator':	'Calculadora de combustível',
    'Send a Suggestion':	'',
    'Submit':	'',
    'Dry':	'',
    'Wet':	'',
    'Sign in':	'',
    'Sign up':	'',
    'Sign out':	'',
    'Change password':	'',
    'Account':	'',
}

print("{")
for i in en:
    if en[i] in translated and translated[en[i]] != '':
        print(f'"{i}": "{translated[en[i]]}",')

print("}")
