en = {
    "byLaps": "By Laps",
    "byStint": "By Stint",
    "calculate": "Calculate",
    "formationLap": "Formation Lap",
    "lapTime": "Lap Time",
    "laps": "Laps",
    "options": "Options",
    "perLap": "Per Lap",
    "save": "Save",
    "stintLength": "Stint/Race Length",
    "estLaps": "Estimated Laps",
    "gallons": "Gallons",
    "litres": "Litres",
    "risky": "Risky",
    "safe": "Safe",
    "car": "Car",
    "carClass": "Class",
    "conditions": "Conditions",
    "selectCombo": "Select Combination",
    "selections": "Selections",
    "track": "Track",
    "clearData": "Clear Data",
    "language": "Language",
    "leaveReview": "Leave a Review",
    "sendSuggestion": "Send a Suggestion",
    "thankYou": "Thank You",
    "units": "Units",
    "dry": "Dry",
    "damp": "Damp",
    "wet": "Wet",
    "themeOptions": "Theme Options",
    "light": "Light",
    "dark": "Dark",
    "system": "System",
    "success": "Success",
    "error": "Error"
}


translated = {
    'By Laps':	'Etter runder',
    'By Stint':	'Etter stint',
    'Calculate': 'Beregn',
    'Formation Lap': 'Formasjonsrunde',
    'Lap Time': 'Rundetid',
    'Laps': 'Runder',
    'Options': 'Alternativer',
    'Per Lap': 'Per runde',
    'Save': 'Lagre',
    'Stint/Race Length': 'Stint/løpslengde',
    'Estimated Laps': 'Antatt runder',
    'Gallons': 'Gallons',
    'Litres': 'Liter',
    'Risky': 'Risikabelt',
    'Safe': 'Trygg',
    'Car': 'Bil',
    'Class': 'Klasse',
    'Conditions': 'Forhold',
    'Select Combination': 'Velg kombinasjon',
    'Selections': 'Valg',
    'Track': 'Bane',
    'Clear Data': 'Fjern data',
    'Language': 'Språk',
    'Leave a Review': 'Legg igjen en anmeldelse',
    'Send a Suggestion': 'Send et forslag',
    'Thank You': 'Tusen takk',
    'Units': 'Enheter',
    'Dry': 'Tørr',
    'Damp': 'Fuktig',
    'Wet': 'Vått',
    'Theme Options': 'Temavalg',
    'Light': 'Lys',
    'Dark': 'Mørk',
    'System': 'System',
}

print("{")
for i in en:
    if en[i] in translated and translated[en[i]] != '':
        print(f'"{i}": "{translated[en[i]]}",')

print("}")
